spring:
  servlet:
    multipart:
      max-file-size: 10MB
    #热部署   对前端修改后 不再需要一次次重启项目
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://192.168.37.192:3306/kaoshi?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /jsps/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.jcww.training.pojo
  configuration:
    map-underscore-to-camel-case: true
    #pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
server:
  port: 8089
logging:
  level:
    com:
      jcww:
        training: debug